### ISSUE TITLE
include credit at the top of the generated changelog

### ISSUE THREAD

**Issue by jfindlay** [tjstansell/salt-changelogs#1]
Thanks for the excellent changelog generator.  Is it possible for you to include a credit line at the top of the generated changelog?  Something similar to https://github.com/saltstack/salt/blob/develop/doc/topics/releases/2015.5.3.rst#L5.

**Comment by tjstansell** [comment]
Change done.

**Comment by jfindlay** [comment]
Awesome, thanks @tjstansell.
